trigger:
  branches:
    include:
    - main


variables:
  BuildConfiguration: 'Release'
  GitVersionVersion: '5.1.1'
  NuGetVersion: '5.3.1'

jobs:
- job: BuildArtifacts
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: build/azure-pipelines-steps.nuget.yml
    parameters:
      GitVersionVersion: $(GitVersionVersion)
      NuGetVersion: $(NuGetVersion)
      BuildConfiguration: $(BuildConfiguration)
      outputDirectory: $(Build.ArtifactStagingDirectory)
      deploy: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq('true', variables['FORCE_DEPLOY']))) 